### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by Conte-harebourd** [Naexys/Unrailed_AI#1]
The module does not seem to be present: ModuleNotFoundError: No module named 'cv2'
![Unrailed](https://user-images.githubusercontent.com/51010031/107566642-6caea600-6be5-11eb-8938-da716ec1a0d2.png)

**Comment by Flowtter** [comment]
Hello,
If you want to play, and you are missing libraries, try

`pip install -r requirements.txt`

If this doesn't work, try to install the latest libraries, each library is specified in the requirements.txt file.

I think Unrailed has changed the icons of the recent tools, you replace them here :

- https://github.com/Flowtter/unrailed-ai/blob/master/src/template_axe.png
- https://github.com/Flowtter/unrailed-ai/blob/master/src/template_pickaxe.png

**Comment by Conte-harebourd** [comment]
The file is not present when ordering #
![Unrailed](https://user-images.githubusercontent.com/51010031/107793733-edd97a80-6d56-11eb-8b61-3d6c8bc93db8.png)
