### ISSUE TITLE
No such file 

### ISSUE THREAD

**Issue by Conte-harebourd** [Naexys/Unrailed_AI#2]
![Unrailed](https://user-images.githubusercontent.com/51010031/107575215-f2375380-6bef-11eb-895a-46f51ca4d6ad.png)

**Comment by Flowtter** [comment]
Hi,
you need to `cd` in my repository, you're not in it.
try `cd Unrailed/Unrailed_AI`
then `pip install -r requirements.txt`
then `python src/main.py` (if it doesn't work, follow the tutorial on the readme).

Moreover, try to keep this discussion in the same thread, this one, I'm closing the other one.
