### ISSUE TITLE
no such 

### ISSUE THREAD

**Issue by Conte-harebourd** [Naexys/Unrailed_AI#3]
![Unrailed](https://user-images.githubusercontent.com/51010031/107793815-06499500-6d57-11eb-9ef9-5e531d0252a4.png)
What did I not do well?

**Comment by Flowtter** [comment]
Hi,
requirements.txt is a
python -r requirements.txt means: "hey can you open the requirements.txt file and install everything in it".
the requirements.txt file is located in `unrailed-ia` and not in the "src" folder,
to be sure you are in the right folder, use the command `dir` which will list all files and directories, once you see the requirements.txt file, you can execute the last command I gave you, which is `pip install -r requirements.txt`

**Comment by Conte-harebourd** [comment]
![Unrailed](https://user-images.githubusercontent.com/51010031/107796239-e9fb2780-6d59-11eb-9b6c-19621a08585c.png)
A new problem has just appeared after ordering `pip install -r requirements.txt`

**Comment by Flowtter** [comment]
You're using a really recent version of python.
Maybe try downgrading  to 3.7, I'm not sure that all libraries I'm using are compatible yet.
Also it seems like you're having issues with Cython and Gnu, try to google them/stackoverflow if downgrading does not fix.

Edit: I updated the libraries, you can just pull and try again the `pip install -r requirements.txt`

**Comment by Conte-harebourd** [comment]
new problem : The DNS server is not authoritative for the zone.

**Comment by Flowtter** [comment]
https://windowsreport.com/dns-server-not-authoritative-for-zone/#:~:text=The%20%E2%80%9CDNS%20server%20not%20authoritative,the%20Windows%20key%20%2B%20S%20hotkey.

**Comment by Conte-harebourd** [comment]
![image](https://user-images.githubusercontent.com/51010031/107988718-e3c2b080-6fd0-11eb-8fb9-3d5c5dc94b7e.png)

**Comment by Flowtter** [comment]
Hi,
You have to install the requirements.

**Comment by Conte-harebourd** [comment]
i did it 
![image](https://user-images.githubusercontent.com/51010031/107991534-18d20180-6fd7-11eb-9c93-c4908d8900c7.png)

**Comment by Conte-harebourd** [comment]
![image](https://user-images.githubusercontent.com/51010031/107991652-5d5d9d00-6fd7-11eb-9c44-9349a6163b3c.png)

**Comment by Flowtter** [comment]
pip install opencv-python

**Comment by Conte-harebourd** [comment]
i did it 
![image](https://user-images.githubusercontent.com/51010031/107992956-1a50f900-6fda-11eb-9116-2e14ffe883c5.png)

**Comment by Flowtter** [comment]
https://stackoverflow.com/questions/54147922/no-module-named-cv2-but-it-is-installed


https://docs.opencv.org/master/d5/de5/tutorial_py_setup_in_windows.html

**Comment by Conte-harebourd** [comment]
![image](https://user-images.githubusercontent.com/51010031/107995456-baa91c80-6fde-11eb-9b30-c7e532fa080e.png)
New problem

**Comment by Flowtter** [comment]
https://pypi.org/project/PyAutoGUI/

If you're missing a library, visit pypi.org
