### ISSUE TITLE
pyautogui doesn't work

### ISSUE THREAD

**Issue by pythonista-blitz** [Naexys/Unrailed_AI#4]
Hi, I'm beginner of Python and try to make unrailed-AI. Your readable code teaches me a lot. Thanks.
But my orange penguin doesn't move at all. so I googled and found that pyautogui doesn't work because of directX.

c.f.  pydirectinput([here](https://pypi.org/project/PyDirectInput/)).

**Comment by Flowtter** [comment]
Hello, unfortunately I have some problems with this project, a lot of code is redundant and I don't like the structure. It's a project I did while learning programming, so I made the wrong choice of library preventing the program to be used under linux for example. Pyautogui is one of them. I plan to work on the project again when I have time, in the meantime, I can only advise you to make a fork and try to fix it!

I am very happy that the project has taught you things and you make me want to work on it again. Good luck!
